name: Deploy static content to Pages

on:
  # push:
  #   branches: ['master']
  #   paths-ignore:
  #     - '**.md'
  #     - '.github/**'
  #     - '.gitignore'
  #     - '**.json'
  #     - '**/**.test.ts'
  #     - '**/**.test.js'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create .env from example
        run: cp .env.example .env

      - name: Inject secrets into .env
        run: |
          echo "VITE_TMDB_TOKEN=${{ secrets.VITE_TMDB_TOKEN }}" >> .env
          echo "VITE_TMDB_URL=${{ secrets.VITE_TMDB_URL }}" >> .env
          echo "VITE_ACCOUNT_ID=${{ secrets.VITE_ACCOUNT_ID }}" >> .env

      - name: Build project
        run: pnpm build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
